"""add admins

Revision ID: e4221cb9f9ad
Revises: a88e24175f31
Create Date: 2020-12-07 22:17:42.006593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4221cb9f9ad'
down_revision = 'a88e24175f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admins', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admins')
    # ### end Alembic commands ###
